{% set name = "django-filebrowser" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-filebrowser-{{ version }}.tar.gz
  sha256: 5ed8da98fc9c5361a1e39e18908cc007d8bae77dd891c9fbe87d8aa9892d7656

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - django-grappelli >=3.0,<3.1
    - pillow
    - six

test:
  imports:
    - filebrowser
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-filebrowser.readthedocs.org
  summary: Media-Management with Grappelli
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
